<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>vertx-parent</artifactId>
        <groupId>io.vertx</groupId>
        <version>19</version>
    </parent>
  <groupId>io.vertx.demos</groupId>
  <artifactId>vertx-demos-mail</artifactId>
  <version>0.0.1</version>

  <packaging>jar</packaging>

  <properties>
    <vertx.version>5.0.0-SNAPSHOT</vertx.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
    <maven-shade-plugin.version>3.2.1</maven-shade-plugin.version>
    <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
    <exec-maven-plugin.version>3.0.0</exec-maven-plugin.version>

    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <log4j2.version>2.20.0</log4j2.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-stack-depchain</artifactId>
        <version>${vertx.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-mail-client</artifactId>
    </dependency>
  <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web</artifactId>
  </dependency>
  <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-core-logging</artifactId>
  </dependency>
<!--      <dependency>-->
<!--          <groupId>org.apache.logging.log4j</groupId>-->
<!--          <artifactId>log4j-api</artifactId>-->
<!--          <version>${log4j2.version}</version>-->
<!--      </dependency>-->
<!--      <dependency>-->
<!--          <groupId>org.apache.logging.log4j</groupId>-->
<!--          <artifactId>log4j-core</artifactId>-->
<!--          <version>${log4j2.version}</version>-->
<!--      </dependency>-->
<!--      <dependency>-->
<!--          <groupId>org.apache.logging.log4j</groupId>-->
<!--          <artifactId>log4j-slf4j-impl</artifactId>-->
<!--          <version>${log4j2.version}</version>-->
<!--      </dependency>-->
  </dependencies>

    <build>
        <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <release>11</release>
        </configuration>
      </plugin>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Main-Class>io.github.gaol.samples.sendmail.MainVerticle</Main-Class>
                                    </manifestEntries>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <outputFile>${project.build.directory}/${project.artifactId}-${project.version}-fat.jar
                            </outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
