version: '2'

services:

  postgres:
    image: postgres:10.10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql