
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tFT%1$tTZ [%4$s] [%2$s] %5$s%6$s%n
java.util.logging.ConsoleHandler.level=FINEST

.level=INFO
io.vertx.ext.mail.level=FINEST
io.vertx.level=INFO
io.netty.util.internal.PlatformDependent.level=SEVERE
