apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        cluster: vertx-demo-app
    spec:
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABELS
              value: 'app=${project.artifactId}'
            - name: JAVA_ARGS
              value: '-Djava.net.preferIPv4Stack=true -Dvertx.jgroups.config=jgroups-k8s.xml -Djgroups.dns.query=${project.artifactId}.default.svc.cluster.local -cluster'

